server:
  contextPath: /
  port: ${port:8083}
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/css,text/html,text/javascript,text/plain,text/xml
  error:
    whitelabel:
      enabled: false

management:
  contextPath: /admin
  port: ${port:8083}

spring:
  mustache:
    suffix: .mustache
