gov-au:
  image: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/ausdtomonitoring-appointments-border-gov-au:IMAGE_TAG
  hostname: appointments-border-gov-au
  environment:
    - RABBITMQ_HOST
    - RABBITMQ_PORT
    - RABBITMQ_USER
    - RABBITMQ_PASSWORD
    - RABBITMQ_VHOST
    - URL
    - PAGELOAD_URI=/login

